# Generated by Django 3.0.7 on 2020-06-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulting2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('student_name', models.CharField(max_length=140)),
                ('student_grade', models.CharField(choices=[('m1', '중학생 1학년'), ('m2', '중학생 2학년'), ('m3', '중학생 3학년'), ('h1', '고등학생 1학년'), ('h2', '고등학생 2학년'), ('h3', '고등학생 3학년')], default='', max_length=20)),
                ('phone_number1', models.CharField(max_length=3)),
                ('phone_number2', models.CharField(max_length=4)),
                ('phone_number3', models.CharField(max_length=4)),
                ('region', models.CharField(max_length=140)),
                ('consulting_time', models.CharField(choices=[('time1', '오전 9시 - 오전 10시'), ('time2', '오전 10시 - 오전 11시'), ('time3', '오전 11시 - 오후 12시'), ('time4', '오후 12시 - 오후 13시'), ('time5', '오후 13시 - 오후 14시'), ('time6', '오후 14시 - 오후 15시'), ('time7', '오후 15시 - 오후 16시'), ('time8', '오후 16시 - 오후 17시'), ('time9', '오후 17시 - 오후 18시'), ('time10', '오후 18시 - 오후 19시'), ('time11', '오후 19시 - 오후 20시'), ('time12', '오후 20시 - 오후 21시')], default='', max_length=12)),
                ('Personal_information_consent', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
