# Generated by Django 3.0.7 on 2020-06-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('student_name', models.CharField(max_length=140)),
                ('student_grade', models.CharField(max_length=140)),
                ('phone_number1', models.CharField(max_length=3)),
                ('phone_number2', models.CharField(max_length=4)),
                ('phone_number3', models.CharField(max_length=4)),
                ('region', models.CharField(max_length=140)),
                ('consulting_time', models.CharField(max_length=140)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
