# Generated by Django 3.0.7 on 2020-06-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulting',
            name='Personal_information_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='consulting',
            name='consulting_time',
            field=models.CharField(choices=[('time1', '오전 9시 - 오전 10시'), ('time2', '오전 10시 - 오전 11시'), ('time3', '오전 11시 - 오후 12시'), ('time4', '오후 12시 - 오후 13시'), ('time5', '오후 13시 - 오후 14시'), ('time6', '오후 14시 - 오후 15시'), ('time7', '오후 15시 - 오후 16시'), ('time8', '오후 16시 - 오후 17시'), ('time9', '오후 17시 - 오후 18시'), ('time10', '오후 18시 - 오후 19시'), ('time11', '오후 19시 - 오후 20시'), ('time12', '오후 20시 - 오후 21시')], default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='consulting',
            name='student_grade',
            field=models.CharField(choices=[('m1', '중학생 1학년'), ('m2', '중학생 2학년'), ('m3', '중학생 3학년'), ('h1', '고등학생 1학년'), ('h2', '고등학생 2학년'), ('h3', '고등학생 3학년')], default='', max_length=20),
        ),
    ]
