# Generated by Django 3.0.6 on 2020-06-02 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LectureCost',
            new_name='LectureGrade',
        ),
        migrations.AlterModelOptions(
            name='lecturegrade',
            options={'verbose_name_plural': '강의대상'},
        ),
        migrations.RenameField(
            model_name='board',
            old_name='lecture_cost',
            new_name='lecture_grade',
        ),
    ]
