# Generated by Django 3.0.7 on 2020-06-17 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20200602_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name_plural': '1. 모든 게시판 관리'},
        ),
        migrations.AlterModelOptions(
            name='boardtype',
            options={'verbose_name_plural': '[게시판 관리] 게시판 종류'},
        ),
        migrations.AlterModelOptions(
            name='courseperiod',
            options={'verbose_name_plural': '강의 게시판 - 수강기간'},
        ),
        migrations.AlterModelOptions(
            name='lecturegrade',
            options={'verbose_name_plural': '강의 게시판 - 강의대상'},
        ),
        migrations.AlterModelOptions(
            name='teachingtextbooks',
            options={'verbose_name_plural': '강의 게시판 - 강의 교재'},
        ),
        migrations.AlterModelOptions(
            name='textbookfeatures',
            options={'verbose_name_plural': '강의 게시판 - 교재 특징'},
        ),
        migrations.RemoveField(
            model_name='board',
            name='address',
        ),
        migrations.RemoveField(
            model_name='board',
            name='baths',
        ),
        migrations.RemoveField(
            model_name='board',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='board',
            name='beds',
        ),
        migrations.RemoveField(
            model_name='board',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='board',
            name='check_out',
        ),
        migrations.RemoveField(
            model_name='board',
            name='city',
        ),
        migrations.RemoveField(
            model_name='board',
            name='country',
        ),
        migrations.RemoveField(
            model_name='board',
            name='guests',
        ),
        migrations.RemoveField(
            model_name='board',
            name='instant_book',
        ),
    ]
